export const linkTitles: [string, string][] = [
  ['/', 'The Complete Lojban Language'],
  ['/chapter01/', 'Chapter 01'],
  ['/chapter02/', 'Chapter 02'],
  ['/chapter03/', 'Chapter 03'],
  ['/chapter04/', 'Chapter 04'],
  ['/chapter05/', 'Chapter 05'],
  ['/chapter06/', 'Chapter 06'],
  ['/chapter07/', 'Chapter 07'],
  ['/chapter08/', 'Chapter 08'],
  ['/chapter09/', 'Chapter 09'],
  ['/chapter10/', 'Chapter 10'],
  ['/chapter11/', 'Chapter 11'],
  ['/chapter12/', 'Chapter 12'],
  ['/chapter13/', 'Chapter 13'],
  ['/chapter14/', 'Chapter 14'],
  ['/chapter15/', 'Chapter 15'],
  ['/chapter16/', 'Chapter 16'],
  ['/chapter17/', 'Chapter 17'],
  ['/chapter18/', 'Chapter 18'],
  ['/chapter19/', 'Chapter 19'],
  ['/chapter20/', 'Chapter 20'],
  ['/chapter21/', 'Chapter 21'],
  ['/glossary/', 'Lojban Word Glossary'],
  ['/general/', 'General Index'],
  ['/words/', 'Lojban Words Index'],
  ['/examples/', 'Examples Index'],
];
